### ISSUE TITLE
Improve promise rejection errors

### ISSUE THREAD

**Issue by DimalChandrasiri** [asgardeo/asgardeo-js-oidc-sdk#24]
**Description:**
Revamp Error codes to match unique errors so that it is easier to differentiate from standard axios errors.

**Comment by brionmario** [comment]
It would be better to create custom exceptions to give more context to errors. Refer [1]

[1] https://github.com/wso2/identity-apps/blob/master/modules/core/src/exceptions/identity-apps-api-exception.ts
